### ISSUE TITLE
glogi/set-level always generates a failed assert 

### ISSUE THREAD

**Issue by KingCode** [lambdaisland/glogi#1]
I am trying to use glogi/set-level, but am getting an error due to line 59 in glogi.cljs:
```
(glogi/set-level` "my-logger.etc" :error)
;;=> (assert (contains? level lvl))
;; throws an error, since level is a fn object
```

**Comment by plexus** [comment]
Thanks! This should be fixed in `0.0-25`. Could you try it out and close the ticket or report back?
