### ISSUE TITLE
Error when using glogc with cljs

### ISSUE THREAD

**Issue by oxalorg** [lambdaisland/glogi#15]
Shouldn't this line be:
https://github.com/lambdaisland/glogi/blob/1925f6d480f4bfe5c3afae8709325778946b02d5/src/lambdaisland/glogc.cljc#L8

`lambdaisland.glogc` instead of `co.gaiwan.log`?

**Comment by plexus** [comment]
yes! can you fix that?

**Comment by alysbrooks** [comment]
@oxalorg I think this issue can be closed?
