### ISSUE TITLE
trying to use kaocha-cljs2 on latest cljs, get 'No such namespace: goog.debug.Logger,'

### ISSUE THREAD

**Issue by henryw374** [lambdaisland/glogi#19]
bc breaking changes in closure :(

**Comment by henryw374** [comment]
I see there is a kaocha cljs2 issue already

**Comment by plexus** [comment]
Yeah sorry, been trying to make some progress on a new release but it's a bit of a yak shave.

**Comment by luposlip** [comment]
So, it's not just me that can't get glogi to work with cljs 1.10.891?

**Comment by rgm** [comment]
Just linking the issue: https://github.com/lambdaisland/kaocha-cljs2/issues/14.

I fixed the breakage in a kaocha-cljs 1.0.107 / clojurescript 1.11.60 project by adding `com.lambdaisland/glogi {:mvn/version "1.1.144"}` explicitly to my deps.edn. The explicit listing overrides the transient 1.0.128 version of glogi pulled in by kaocha-cljs.
