### ISSUE TITLE
log/console-autoinstall! always accumulates

### ISSUE THREAD

**Issue by torkus** [lambdaisland/glogi#2]
Both of these approaches to installing the console log event handler just once in an environment where figwheel reloads code fails. The log messages are repeated N times for each subsequent code reload:

```cljs
(defonce on-initial-load
  (do
    (log/console-autoinstall!)
    true)))
```
```cljs
(events/listen js/window "load"
               (fn [_]
                 (log/console-autoinstall!)))
```

examples taken from here: https://figwheel.org/docs/reloadable_code.html

**Comment by plexus** [comment]
Figwheel installs its own handler, so `console-autoinstall!` shouldn't be needed when using Figwheel. Not sure why it's being added twice, this might be an unintended interplay between the handler that Figwheel installs and the one added by Glogi.
